-- MySQL Script generated by MySQL Workbench
-- Fri May  3 00:34:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CoursesProject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CoursesProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CoursesProject` DEFAULT CHARACTER SET utf8 ;
USE `CoursesProject` ;

-- -----------------------------------------------------
-- Table `CoursesProject`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoursesProject`.`Clients` (
  `idClients` INT NOT NULL AUTO_INCREMENT,
  `idCar` INT NOT NULL,
  `SecondName` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `MiddleName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `House` VARCHAR(45) NOT NULL,
  `Corpus` VARCHAR(45) NULL,
  `Flat` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `DriverLicenseNumber` VARCHAR(45) NOT NULL,
  `AdditionalInformation` LONGTEXT NULL,
  PRIMARY KEY (`idClients`),
  INDEX `idCar` (`idCar` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CoursesProject`.`Car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoursesProject`.`Car` (
  `idCar` INT NOT NULL AUTO_INCREMENT,
  `idBooking` INT NOT NULL,
  `idRentalCenter` INT NOT NULL,
  `Stamp` VARCHAR(45) NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  `YearOfRelease` YEAR(4) NOT NULL,
  `Status` ENUM('Available', 'Leased', 'In service') NOT NULL,
  `TheCostOfRent` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idCar`),
  INDEX `idRentalCenter` (`idRentalCenter` ASC) INVISIBLE,
  INDEX `idBooking` (`idBooking` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CoursesProject`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoursesProject`.`Booking` (
  `idBooking` INT NOT NULL,
  `idClients` INT NOT NULL,
  `idCar` INT NOT NULL,
  `idRentalCenter` INT NOT NULL,
  `RentalStartDate` DATE NOT NULL,
  `TheEndDateOfTheLease` DATE NOT NULL,
  `TheTotalCostOfTheRental` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idBooking`),
  INDEX `idClients_idx` (`idClients` ASC) VISIBLE,
  INDEX `idCar_idx` (`idCar` ASC) VISIBLE,
  INDEX `idRentalCenter_idx` (`idRentalCenter` ASC) VISIBLE,
  CONSTRAINT `idClients`
    FOREIGN KEY (`idClients`)
    REFERENCES `CoursesProject`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCar`
    FOREIGN KEY (`idCar`)
    REFERENCES `CoursesProject`.`Car` (`idCar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRentalCenter`
    FOREIGN KEY (`idRentalCenter`)
    REFERENCES `CoursesProject`.`RentalCenter` (`idRentalCenter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CoursesProject`.`RentalCenter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoursesProject`.`RentalCenter` (
  `idRentalCenter` INT NOT NULL AUTO_INCREMENT,
  `idCar` INT NOT NULL,
  `idBooking` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `House` VARCHAR(45) NOT NULL,
  `Corpus` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `NumberOfAvailableCars` INT NOT NULL,
  `ServiceServices` LONGTEXT NULL,
  PRIMARY KEY (`idRentalCenter`),
  INDEX `idBooking` (`idBooking` ASC) INVISIBLE,
  CONSTRAINT `idBooking`
    FOREIGN KEY (`idBooking`)
    REFERENCES `CoursesProject`.`Booking` (`idBooking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
